workflows:
  ios-build:
    name: iOS Build for V-Card
    environment:
      groups:
        - apple_credentials # Va conține certificatul și profilul de provisioning
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build iOS App
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - "your-email@example.com"
